language: python

python:
  - 3.6
  - 3.7

matrix:
  include:
    - name: flake8
      python: 3.7
      script: tox -e flake8

install: pip install tox-travis
script: tox

notifications:
  email:
    on_success: never
    on_failure: always
